export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const TOGGLE_ACTION_MODE = "TOGGLE_ACTION_MODE";
export const UPDATE_STORE_DATA = "UPDATE_STORE_DATA";
export const UPDATE_STORE_NAME = "UPDATE_STORE_NAME";
export const UPDATE_ITEMS = "UPDATE_ITEMS";
export const CLEAR_STATE = "CLEAR_STATE";