export const ADD_ARTICLE = "ADD_ARTICLE";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const TOGGLE_ACTION_MODE = "TOGGLE_ACTION_MODE";
export const UPDATE_STORE_DATA = "UPDATE_STORE_DATA";