export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const TOGGLE_ACTION_MODE = "TOGGLE_ACTION_MODE";
export const STORE_ITEM_EDIT_MODE = "STORE_ITEM_EDIT_MODE";
export const UPDATE_STORE_DATA = "UPDATE_STORE_DATA";
export const UPDATE_STORE_NAME = "UPDATE_STORE_NAME";
export const UPDATE_ALL_ITEMS = "UPDATE_ALL_ITEMS";
export const ADD_ONE_ITEM = "UPDATE_ONE_ITEM";
export const CLEAR_STATE = "CLEAR_STATE";
